[package]
name = "workflow"
version.workspace = true
publish = false
edition.workspace = true

[dependencies]
gpui-kit.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
mermaid_renderer = { path = "../mermaid_renderer" }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
