use super::*;

pub(super) struct BoardDataState {
    pub(super) board_id: Option<u32>,
    pub(super) lists: Vec<BoardListState>,
    pub(super) labels: Vec<BoardLabel>,
}

pub(super) struct RelatedNotesState {
    pub(super) picker: related_notes::RelatedNotePickerState,
    pub(super) by_item: HashMap<
        storage::workspace::links::WorkspaceItemRef,
        Vec<storage::workspace::links::RelatedNote>,
    >,
    pub(super) catalog: Arc<Vec<storage::workspace::links::WorkspaceCatalogEntry>>,
    pub(super) completion_provider: workspace::WikiLinkCompletionProvider,
    pub(super) error: Option<SharedString>,
}

pub(super) struct BoardMutationState {
    pub(super) load_error: Option<SharedString>,
    pub(super) mutation_error: Option<SharedString>,
    pub(super) load_request: workspace::RequestTracker,
    pub(super) layout_commit_task: Option<Task<()>>,
    pub(super) loaded_generation: Option<u64>,
    pub(super) local_generation: u64,
}

pub(super) struct BoardPropertiesState {
    pub(super) data: storage::board::properties::BoardProperties,
    pub(super) values: HashMap<(i64, i64), storage::board::properties::PropertyValue>,
    pub(super) saved_views: Vec<storage::board::properties::BoardView>,
    pub(super) active_view_id: Option<i64>,
    pub(super) active_view_config: storage::board::properties::BoardViewConfig,
    pub(super) view_config_dirty: bool,
    pub(super) view_load_warnings: Vec<SharedString>,
    pub(super) update_error: Option<SharedString>,
    pub(super) field_errors: HashMap<(i64, i64), SharedString>,
    pub(super) saving_values: HashSet<(i64, i64)>,
    pub(super) property_panel_open: bool,
    pub(super) property_form_open: bool,
    pub(super) fields_panel_open: bool,
    pub(super) view_panel_open: bool,
    pub(super) new_view_form_open: bool,
    pub(super) sort_panel_open: bool,
    pub(super) new_property_kind: storage::board::properties::PropertyKind,
    pub(super) new_property_input: Entity<InputState>,
    pub(super) rename_property_input: Entity<InputState>,
    pub(super) renaming_property_id: Option<i64>,
    pub(super) new_property_option_input: Entity<InputState>,
    pub(super) rename_property_option_input: Entity<InputState>,
    pub(super) renaming_property_option_id: Option<i64>,
    pub(super) adding_property_option_id: Option<i64>,
    pub(super) property_value_input: Entity<InputState>,
    pub(super) property_date_picker: Entity<DatePickerState>,
    pub(super) editing_property_id: Option<i64>,
    pub(super) property_select_search_input: Entity<InputState>,
    pub(super) selecting_property_id: Option<i64>,
    pub(super) new_view_input: Entity<InputState>,
    pub(super) rename_view_input: Entity<InputState>,
    pub(super) renaming_view_id: Option<i64>,
    pub(super) filter_value_input: Entity<InputState>,
    pub(super) editing_filter_property_id: Option<i64>,
    pub(super) next_update_revision: u64,
    pub(super) update_revisions: HashMap<(i64, i64), u64>,
    pub(super) persisted_revisions: Arc<tokio::sync::Mutex<HashMap<(i64, i64), u64>>>,
}

pub(super) struct EntryEditingState {
    pub(super) adding_list: bool,
    pub(super) open: bool,
    pub(super) dialog: EntryDialog,
    pub(super) new_list_input: Entity<InputState>,
    pub(super) dialog_title_input: Entity<InputState>,
    pub(super) dialog_description_input: Entity<TextareaState>,
    pub(super) title_input: Entity<InputState>,
    pub(super) description_input: Entity<EditorState>,
    pub(super) due_date_picker: Entity<DatePickerState>,
    pub(super) new_label_input: Entity<InputState>,
    pub(super) rename_label_input: Entity<InputState>,
    pub(super) new_checklist_item_input: Entity<InputState>,
    pub(super) rename_checklist_item_input: Entity<InputState>,
    pub(super) rename_list_input: Entity<InputState>,
    pub(super) renaming_list_id: Option<u32>,
    pub(super) pending_list_id: Option<u32>,
    pub(super) renaming_label_id: Option<u32>,
    pub(super) renaming_checklist_item_id: Option<u32>,
    pub(super) selected_label_color: SharedString,
    pub(super) next_temporary_list_id: u32,
    pub(super) next_temporary_card_id: u32,
    pub(super) next_checklist_item_position: i32,
    pub(super) next_due_date_update_revision: u64,
    pub(super) persisted_due_date_revisions: Arc<tokio::sync::Mutex<HashMap<u32, u64>>>,
    pub(super) attachment_preview_paths: HashMap<u32, PathBuf>,
}
