[package]
name = "quick_capture"
version.workspace = true
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
gpui-kit.workspace = true
runtime = { path = "../runtime" }
storage = { path = "../storage" }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
