[package]
name = "storage"
version.workspace = true
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
entity = { path = "../entity" }
sea-orm.workspace = true

[dev-dependencies]
migration = { path = "../migration" }
tempfile = "3.23"
tokio.workspace = true
