[package]
name = "storage"
version.workspace = true
publish = false
edition.workspace = true

[dependencies]
entity = { path = "../entity" }
anyhow.workspace = true
chrono.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
migration = { path = "../migration" }
tempfile = "3.23"
