//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "board")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub title: String,
    pub project_id: Option<i64>,
    #[sea_orm(has_many)]
    pub cards: HasMany<super::card::Entity>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub project: HasOne<super::project::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
