//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "card")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub title: String,
    pub board_id: i64,
    #[sea_orm(
        belongs_to,
        from = "board_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub board: HasOne<super::board::Entity>,
    #[sea_orm(has_many)]
    pub entries: HasMany<super::entry::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
