//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub title: String,
    pub description: String,
    pub card_id: i64,
    pub position: i32,
    pub due_on: Option<String>,
    pub deleted_at: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "card_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub card: HasOne<super::card::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
