//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entry_attachment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub entry_id: i64,
    pub file_name: String,
    #[sea_orm(
        belongs_to,
        from = "entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub entry: HasOne<super::entry::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
