//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod board;
pub mod board_label;
pub mod card;
pub mod entry;
pub mod entry_attachment;
pub mod entry_checklist_item;
pub mod entry_label;
pub mod note;
pub mod project;
