//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::board::Entity as Board;
pub use super::board_label::Entity as BoardLabel;
pub use super::card::Entity as Card;
pub use super::entry::Entity as Entry;
pub use super::entry_attachment::Entity as EntryAttachment;
pub use super::entry_checklist_item::Entity as EntryChecklistItem;
pub use super::entry_label::Entity as EntryLabel;
pub use super::note::Entity as Note;
pub use super::project::Entity as Project;
