[package]
name = "document_editor"
version.workspace = true
publish = false
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component = { workspace = true, features = ["tree-sitter-languages"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["sync"] }
serde.workspace = true
serde_json.workspace = true
toml_edit.workspace = true
image.workspace = true
lsp-types.workspace = true
chrono.workspace = true
tree-sitter.workspace = true
tree-sitter-json.workspace = true
merman.workspace = true
lol_html = "2.9"
dprint-plugin-json = "0.22.1"
dprint-plugin-markdown = "0.22.1"
storage = { path = "../storage" }
app_services = { path = "../app_services" }
app_settings = { path = "../app_settings" }
workspace_ui = { path = "../workspace_ui" }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
tempfile = "3.23"
sea-orm.workspace = true
migration = { path = "../migration" }
entity = { path = "../entity" }
test_support = { path = "../test_support" }
